#######################
# Server Configuration
#######################

server:
  port: 8099
  servlet:
    context-path: /shs-traduction
    session:
      timeout: 30m

#######################
# Spring configuration
#######################
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/open-traduction
    password: postgres
    username: postgres
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/changelog/db.changelog.yaml
#######################
# Deepl configuration
#######################
deepl:
  enable: false
  key: test
