#######################
# Server Configuration
#######################

server:
  port: 9090
  servlet:
    context-path: /shs-traduction
    session:
      timeout: 125m
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto

admin:
  apikey: ot_1739224206613pm58lw3n2hbh9nb55pmqrb93g7xfph5m5dl68x0fn38fqvk6

primefaces:
  theme: bootstrap

#######################
# Spring configuration
#######################
spring:
  main:
    allow-bean-definition-overriding: true
  threads:
    virtual:
      enabled: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/open-traduction
    password: postgres
    username: postgres
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/changelog/db.changelog.yaml
#######################
# Deepl configuration
#######################
deepl:
  enable: false
  key: test
