#######################
# Server Configuration
#######################

server:
  port: 8087
  servlet:
    context-path: /shs-traduction
    session:
      timeout: 30m

tomcat:
  ajp:
    port: 9090
    remoteauthentication: false
    enabled: true

#######################
# Spring configuration
#######################
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/shs
    password: frantiq2014
    username: pactols
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/changelog/db.changelog.yaml

#######################
# Logging configuration
#######################
logging:
  config: classpath:logback-local.xml

#######################
# Deepl configuration
#######################
deepl:
  enable: false
  key: test
