#######################
# Server Configuration
#######################

server:
  port: 8099
  tomcat:
    max-threads: 12
    max-connections: 1000
  servlet:
    context-path: /shs-traduction

#######################
# Spring configuration
#######################
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .xhtml
  datasource:
    url: jdbc:postgresql://localhost:5432/open-traduction
    password: postgres
    username: postgres
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/changelog/db.changelog.yaml

#######################
# Logging configuration
#######################
logging:
  config: classpath:logback-local.xml

#######################
# Deepl configuration
#######################
deepl:
  enable: false
  key: test
